import { jsPDF } from 'jspdf'

function addSectionTitle(doc, text, y) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(30, 41, 59)
  doc.text(text, 14, y)
  doc.setDrawColor(226, 232, 240)
  doc.line(14, y + 2, 196, y + 2)
  return y + 10
}

function wrapText(doc, text, x, y, maxWidth, lineHeight) {
  const lines = doc.splitTextToSize(text, maxWidth)
  doc.text(lines, x, y)
  return y + lines.length * lineHeight
}

export function exportProfilePdf({ user, repos, scoreResult, fixes, insights }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 50

  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, pageWidth, 90, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text(user.name || user.login, 40, 40)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(`@${user.login} · GitHub Profile Report`, 40, 60)
  doc.setFontSize(9)
  doc.text(new Date().toLocaleDateString('en-US', { dateStyle: 'long' }), 40, 76)

  y = 120

  doc.setTextColor(30, 41, 59)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  doc.text(`${scoreResult.total}/100`, 40, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text('Overall Resume Score', 40, y + 16)

  y += 50
  y = addSectionTitle(doc, 'Score Breakdown', y)
  doc.setFontSize(10)
  doc.setTextColor(51, 65, 85)
  scoreResult.categories.forEach((c) => {
    doc.text(`${c.label}`, 18, y)
    doc.text(`${c.score}/${c.max}`, 170, y, { align: 'right' })
    y += 16
  })

  y += 10
  y = addSectionTitle(doc, 'Profile Overview', y)
  doc.setFontSize(10)
  doc.setTextColor(51, 65, 85)
  const overview = [
    `Followers: ${user.followers}`,
    `Following: ${user.following}`,
    `Public Repos: ${repos.length}`,
    `Location: ${user.location || '—'}`,
    `Company: ${user.company || '—'}`,
  ]
  overview.forEach((line) => {
    doc.text(line, 18, y)
    y += 15
  })

  if (fixes?.length) {
    y += 8
    y = addSectionTitle(doc, 'Actionable Fixes', y)
    doc.setFontSize(9.5)
    fixes.slice(0, 6).forEach((f) => {
      if (y > 760) {
        doc.addPage()
        y = 40
      }
      doc.setTextColor(30, 41, 59)
      doc.setFont('helvetica', 'bold')
      doc.text(`• ${f.title} (${f.priority} priority)`, 18, y)
      y += 13
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(71, 85, 105)
      y = wrapText(doc, f.detail, 22, y, 550, 12)
      y += 6
    })
  }

  if (insights?.summary) {
    if (y > 700) {
      doc.addPage()
      y = 40
    }
    y += 8
    y = addSectionTitle(doc, 'AI Career Insights', y)
    doc.setFontSize(9.5)
    doc.setTextColor(71, 85, 105)
    y = wrapText(doc, insights.summary, 18, y, 555, 12)
  }

  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text('Generated by Profile Analyzer', 40, doc.internal.pageSize.getHeight() - 20)

  doc.save(`${user.login}-github-report.pdf`)
}
